# -*- coding: utf-8 -*-
"""AWS Terraform.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12K2kbpIMKWyCKgY6KrLI2BtJRMKtWlsV
"""

!apt-get install unzip -y
!wget https://releases.hashicorp.com/terraform/1.7.5/terraform_1.7.5_linux_amd64.zip
!unzip terraform_1.7.5_linux_amd64.zip
!mv terraform /usr/local/bin/
!terraform -version

# Commented out IPython magic to ensure Python compatibility.
!mkdir -p aws_two_tier/modules/{vpc,ec2,rds}
# %cd aws_two_tier

# Commented out IPython magic to ensure Python compatibility.
# %%writefile main.tf
# terraform {
#   required_providers {
#     aws = {
#       source  = "hashicorp/aws"
#       version = "~> 5.0"
#     }
#   }
#   required_version = ">= 1.3.0"
# }
# 
# provider "aws" {
#   region = var.aws_region
# }
# 
# module "vpc" {
#   source          = "./modules/vpc"
#   vpc_cidr        = var.vpc_cidr
#   public_subnets  = var.public_subnets
#   private_subnets = var.private_subnets
# }
# 
# module "ec2" {
#   source         = "./modules/ec2"
#   vpc_id         = module.vpc.vpc_id
#   public_subnets = module.vpc.public_subnets
#   key_name       = var.key_name
# }
# 
# module "rds" {
#   source      = "./modules/rds"
#   db_subnets  = module.vpc.private_subnets
#   db_username = var.db_username
#   db_password = var.db_password
# }
#

# Commented out IPython magic to ensure Python compatibility.
# %%writefile variables.tf
# variable "aws_region"       { default = "us-east-1" }
# variable "vpc_cidr"         { default = "10.0.0.0/16" }
# variable "public_subnets"   { default = ["10.0.1.0/24", "10.0.2.0/24"] }
# variable "private_subnets"  { default = ["10.0.3.0/24", "10.0.4.0/24"] }
# variable "key_name"         { default = "my-key" }
# variable "db_username"      { default = "admin" }
# variable "db_password"      { default = "Password123!" }
#

# Commented out IPython magic to ensure Python compatibility.
# %%writefile outputs.tf
# output "vpc_id"        { value = module.vpc.vpc_id }
# output "ec2_public_ip" { value = module.ec2.public_ip }
# output "rds_endpoint"  { value = module.rds.db_endpoint }
#

# Commented out IPython magic to ensure Python compatibility.
# %%writefile modules/vpc/main.tf
# resource "aws_vpc" "main" {
#   cidr_block           = var.vpc_cidr
#   enable_dns_support   = true
#   enable_dns_hostnames = true
# }
# 
# resource "aws_subnet" "public" {
#   count                   = length(var.public_subnets)
#   vpc_id                  = aws_vpc.main.id
#   cidr_block              = var.public_subnets[count.index]
#   map_public_ip_on_launch = true
# }
# 
# resource "aws_subnet" "private" {
#   count      = length(var.private_subnets)
#   vpc_id     = aws_vpc.main.id
#   cidr_block = var.private_subnets[count.index]
# }
# 
# output "vpc_id"          { value = aws_vpc.main.id }
# output "public_subnets"  { value = aws_subnet.public[*].id }
# output "private_subnets" { value = aws_subnet.private[*].id }
#

# Commented out IPython magic to ensure Python compatibility.
# %%writefile modules/vpc/variables.tf
# variable "vpc_cidr" {
#   description = "CIDR block for the VPC"
#   type        = string
# }
# variable "public_subnets" {
#   description = "List of public subnet CIDRs"
#   type        = list(string)
# }
# variable "private_subnets" {
#   description = "List of private subnet CIDRs"
#   type        = list(string)
# }
#

# Commented out IPython magic to ensure Python compatibility.
# %%writefile modules/ec2/main.tf
# resource "aws_instance" "web" {
#   ami           = "ami-0c02fb55956c7d316" # Amazon Linux 2 (us-east-1)
#   instance_type = "t2.micro"
#   subnet_id     = element(var.public_subnets, 0)
#   key_name      = var.key_name
# }
# 
# output "public_ip" { value = aws_instance.web.public_ip }
#

# Commented out IPython magic to ensure Python compatibility.
# %%writefile modules/ec2/variables.tf
# variable "vpc_id" {}
# variable "public_subnets" { type = list(string) }
# variable "key_name" {}
#

# Commented out IPython magic to ensure Python compatibility.
# %%writefile modules/rds/main.tf
# resource "aws_db_subnet_group" "db_subnet" {
#   name       = "main-db-subnet"
#   subnet_ids = var.db_subnets
# }
# 
# resource "aws_db_instance" "main" {
#   identifier             = "mydb"
#   allocated_storage      = 20
#   engine                 = "mysql"
#   engine_version         = "8.0"
#   instance_class         = "db.t3.micro"
#   username               = var.db_username
#   password               = var.db_password
#   db_subnet_group_name   = aws_db_subnet_group.db_subnet.name
#   skip_final_snapshot    = true
# }
# 
# output "db_endpoint" { value = aws_db_instance.main.endpoint }
#

# Commented out IPython magic to ensure Python compatibility.
# %%writefile modules/rds/variables.tf
# variable "db_subnets" {
#   description = "List of subnet IDs for RDS subnet group"
#   type        = list(string)
# }
# variable "db_username" {
#   description = "Username for RDS instance"
#   type        = string
# }
# variable "db_password" {
#   description = "Password for RDS instance"
#   type        = string
# }
#

!terraform init
!terraform validate

!terraform validate